import type { DateSpot } from '@/types/dateSpots'

export const DATE_SPOTS_MOCK: DateSpot[] = [

  // ── Jerusalem ──────────────────────────────────────────────────────────────

  {
    id: 'jlm-1',
    name: 'לובי מלון המלך דוד',
    city: 'ירושלים',
    region: 'jerusalem',
    category: 'hotel_lobby',
    vibe: 'אלגנטי ומרשים. לובי מפואר עם נוף לחומות העיר העתיקה. אידיאלי לפגישה ראשונה רשמית.',
    address: 'רחוב המלך דוד 23, ירושלים',
    googleMapsUrl: 'https://maps.google.com/?q=King+David+Hotel+Jerusalem',
    kosher: true,
    priceRange: '₪₪₪',
    averageRating: 4.8,
    reviewCount: 3,
    reviews: [
      { id: 'r1', authorName: 'מ.כ', rating: 5, text: 'מקום מדהים, אווירה נעימה מאוד. יצאנו מרוצים.', createdAt: '2026-03-10' },
      { id: 'r2', authorName: 'ד.ל', rating: 5, text: 'שירות מעולה, נוף לחומות — ממליץ בחום!', createdAt: '2026-02-20' },
      { id: 'r3', authorName: 'ר.א', rating: 4, text: 'יקר קצת, אבל שווה כל שקל. מקום עם ווב.', createdAt: '2026-01-15' },
    ],
  },
  {
    id: 'jlm-2',
    name: 'גן סאקר',
    city: 'ירושלים',
    region: 'jerusalem',
    category: 'park',
    vibe: 'פארק ירוק ושקט במרכז ירושלים. מסלולי הליכה, אגם קטן, ומקומות ישיבה נעימים בצל.',
    address: 'גן סאקר, ירושלים',
    googleMapsUrl: 'https://maps.google.com/?q=Sacher+Park+Jerusalem',
    priceRange: '₪',
    averageRating: 4.5,
    reviewCount: 2,
    reviews: [
      { id: 'r4', authorName: 'נ.פ', rating: 5, text: 'שקט, ירוק, מרגיע. מושלם לטיול ראשון.', createdAt: '2026-03-05' },
      { id: 'r5', authorName: 'ש.מ', rating: 4, text: 'נעים מאוד בשעות הבוקר. מומלץ!', createdAt: '2026-02-01' },
    ],
  },
  {
    id: 'jlm-3',
    name: 'מסעדת מונטיפיורי',
    city: 'ירושלים',
    region: 'jerusalem',
    category: 'restaurant',
    vibe: 'מסעדת שף אלגנטית בשכונת טלביה. תפריט ים תיכוני עשיר, אווירה אינטימית ותאורה נמוכה.',
    address: 'רחוב שמואל הנגיד 7, ירושלים',
    googleMapsUrl: 'https://maps.google.com/?q=Montefiore+Restaurant+Jerusalem',
    kosher: true,
    priceRange: '₪₪₪',
    averageRating: 4.7,
    reviewCount: 2,
    reviews: [
      { id: 'r6', authorName: 'א.ג', rating: 5, text: 'אוכל פנטסטי ואווירה רומנטית. הלכנו שוב!', createdAt: '2026-03-20' },
      { id: 'r7', authorName: 'ל.ס', rating: 4, text: 'מקום מיוחד, שירות אדיב. קצת מחכים.', createdAt: '2026-02-14' },
    ],
  },
  {
    id: 'jlm-4',
    name: 'טיילת ארמון הנציב',
    city: 'ירושלים',
    region: 'jerusalem',
    category: 'quiet',
    vibe: 'טיילת עם נוף פנורמי על כל ירושלים. שקטה, יפה ומתאימה לשיחות ארוכות תוך כדי הליכה.',
    address: 'ארמון הנציב, ירושלים',
    googleMapsUrl: 'https://maps.google.com/?q=Haas+Promenade+Jerusalem',
    priceRange: '₪',
    averageRating: 4.9,
    reviewCount: 3,
    reviews: [
      { id: 'r8', authorName: 'ע.ב', rating: 5, text: 'הנוף מדהים! הרגשנו כמו בסרט.', createdAt: '2026-03-15' },
      { id: 'r9', authorName: 'מ.ד', rating: 5, text: 'כל פעם שאנחנו בא"י זה המקום הראשון שאנחנו הולכים.', createdAt: '2026-02-28' },
      { id: 'r10', authorName: 'ש.ר', rating: 5, text: 'שקט, רוחני, יפהפה. ממליץ בעצם עין.', createdAt: '2026-01-20' },
    ],
  },

  // ── Center ────────────────────────────────────────────────────────────────

  {
    id: 'ctr-1',
    name: 'לובי מלון Norman',
    city: 'תל אביב',
    region: 'center',
    category: 'hotel_lobby',
    vibe: 'בוטיק מלון יוקרתי בלב תל אביב. עיצוב וינטאג׳ אלגנטי, קוקטיילים ואווירה ספרותית.',
    address: 'רחוב נחמני 23, תל אביב',
    googleMapsUrl: 'https://maps.google.com/?q=The+Norman+Hotel+Tel+Aviv',
    priceRange: '₪₪₪',
    averageRating: 4.6,
    reviewCount: 2,
    reviews: [
      { id: 'r11', authorName: 'ר.כ', rating: 5, text: 'מקום קסום. העיצוב מרהיב ואנשים מעניינים.', createdAt: '2026-03-08' },
      { id: 'r12', authorName: 'נ.א', rating: 4, text: 'יקר, אבל האווירה שווה. מגיעים מוכנים להוציא.', createdAt: '2026-02-10' },
    ],
  },
  {
    id: 'ctr-2',
    name: 'שדרות רוטשילד',
    city: 'תל אביב',
    region: 'center',
    category: 'quiet',
    vibe: 'שדרה מוצלת ורחבה בלב תל אביב. ספסלים נוחים, קפה נייד, ואווירה עירונית חיה ונעימה.',
    address: 'שדרות רוטשילד, תל אביב',
    googleMapsUrl: 'https://maps.google.com/?q=Rothschild+Blvd+Tel+Aviv',
    priceRange: '₪',
    averageRating: 4.3,
    reviewCount: 2,
    reviews: [
      { id: 'r13', authorName: 'י.ל', rating: 4, text: 'קלאסי ונעים. אוהב לטייל שם בכל עונה.', createdAt: '2026-03-01' },
      { id: 'r14', authorName: 'ג.מ', rating: 5, text: 'אמרנו "בוא ניהלך קצת" ונהיינו שם 3 שעות!', createdAt: '2026-02-05' },
    ],
  },
  {
    id: 'ctr-3',
    name: 'מסעדת Alena',
    city: 'תל אביב',
    region: 'center',
    category: 'restaurant',
    vibe: 'מסעדת שף בסגנון ים תיכוני עם חומרי גלם מקומיים. אינטימית, טעימה ומתאימה לדייט.',
    address: 'רחוב הרכסים 1, תל אביב',
    googleMapsUrl: 'https://maps.google.com/?q=Alena+Restaurant+Tel+Aviv',
    kosher: false,
    priceRange: '₪₪₪',
    averageRating: 4.7,
    reviewCount: 2,
    reviews: [
      { id: 'r15', authorName: 'ס.פ', rating: 5, text: 'אוכל ברמה אחרת לגמרי. חוויה שאי אפשר לשכוח.', createdAt: '2026-03-18' },
      { id: 'r16', authorName: 'מ.ו', rating: 4, text: 'טעים מאוד, אווירה נפלאה. ממליצה.', createdAt: '2026-02-22' },
    ],
  },
  {
    id: 'ctr-4',
    name: 'גן לאומי תל אביב (הפארק הלאומי)',
    city: 'תל אביב',
    region: 'center',
    category: 'park',
    vibe: 'פארק עירוני גדול עם אגם, אתרי עתיקות ומסלולי הליכה. שלווה ירוקה באמצע העיר.',
    address: 'רחוב קפלן, תל אביב',
    googleMapsUrl: 'https://maps.google.com/?q=Tel+Aviv+National+Park',
    priceRange: '₪',
    averageRating: 4.4,
    reviewCount: 2,
    reviews: [
      { id: 'r17', authorName: 'ד.ה', rating: 4, text: 'שקט ויפה, נחמד לפיקניק קטן.', createdAt: '2026-03-03' },
      { id: 'r18', authorName: 'ח.ב', rating: 5, text: 'האגם מרהיב בשקיעה. המלצה חמה!', createdAt: '2026-01-30' },
    ],
  },
  {
    id: 'ctr-5',
    name: 'מסעדת "הים"',
    city: 'הרצליה פיתוח',
    region: 'center',
    category: 'restaurant',
    vibe: 'מסעדת דגים על הים בהרצליה. גלים, אוויר ים, שקיעה מרהיבה ואוכל טרי. פשוט מושלם.',
    address: 'מרינה הרצליה, הרצליה',
    googleMapsUrl: 'https://maps.google.com/?q=Marina+Herzliya',
    kosher: true,
    priceRange: '₪₪',
    averageRating: 4.6,
    reviewCount: 2,
    reviews: [
      { id: 'r19', authorName: 'ע.צ', rating: 5, text: 'שקיעה + ים + אוכל טוב = חווית דייט מושלמת!', createdAt: '2026-03-12' },
      { id: 'r20', authorName: 'ל.נ', rating: 4, text: 'יפה מאוד, קצת קר בחורף אבל שווה.', createdAt: '2026-01-08' },
    ],
  },

  // ── North ─────────────────────────────────────────────────────────────────

  {
    id: 'nrt-1',
    name: 'טיילת הכנרת (טבריה)',
    city: 'טבריה',
    region: 'north',
    category: 'quiet',
    vibe: 'טיילת נוף לכנרת עם נוף מרהיב על הים. שקטה בשעות הבוקר, חיה בערב. רומנטית תמיד.',
    address: 'טיילת הכנרת, טבריה',
    googleMapsUrl: 'https://maps.google.com/?q=Tiberias+Promenade',
    priceRange: '₪',
    averageRating: 4.7,
    reviewCount: 2,
    reviews: [
      { id: 'r21', authorName: 'כ.ס', rating: 5, text: 'הכנרת בשקיעה זה פשוט קסום. לא שכחנו.', createdAt: '2026-03-22' },
      { id: 'r22', authorName: 'ר.ד', rating: 4, text: 'מקום מדהים לשיחה ארוכה.', createdAt: '2026-02-16' },
    ],
  },
  {
    id: 'nrt-2',
    name: 'גן לאומי בניאס',
    city: 'בניאס',
    region: 'north',
    category: 'park',
    vibe: 'מפל מים עוצר נשימה בצפון הגולן. מסלולי הליכה בין עצים ומים. הרפתקה טבעית מושלמת.',
    address: 'גן לאומי בניאס, רמת הגולן',
    googleMapsUrl: 'https://maps.google.com/?q=Banias+Nature+Reserve',
    priceRange: '₪',
    averageRating: 4.9,
    reviewCount: 3,
    reviews: [
      { id: 'r23', authorName: 'א.מ', rating: 5, text: 'אחד המקומות היפים ביותר בארץ. חובה!', createdAt: '2026-03-25' },
      { id: 'r24', authorName: 'נ.ד', rating: 5, text: 'הלכנו ביחד, חזרנו עם תכנית חיים.', createdAt: '2026-02-18' },
      { id: 'r25', authorName: 'ב.פ', rating: 5, text: 'המפל — תן לזה לדבר בעדו. מהמם.', createdAt: '2026-01-05' },
    ],
  },
  {
    id: 'nrt-3',
    name: 'לובי מלון רימונים גלי כנרת',
    city: 'טבריה',
    region: 'north',
    category: 'hotel_lobby',
    vibe: 'מלון על שפת הכנרת. לובי עם נוף ישיר לים, ספות נוחות ואווירה כפרית-אלגנטית.',
    address: 'מלון רימונים גלי כנרת, טבריה',
    googleMapsUrl: 'https://maps.google.com/?q=Rimonim+Gal+Hotel+Tiberias',
    kosher: true,
    priceRange: '₪₪',
    averageRating: 4.4,
    reviewCount: 2,
    reviews: [
      { id: 'r26', authorName: 'מ.ג', rating: 4, text: 'נוח ונעים, נוף לים מהמם.', createdAt: '2026-03-02' },
      { id: 'r27', authorName: 'ש.ד', rating: 5, text: 'האווירה בלובי ממש מרגיעה ויפה.', createdAt: '2026-01-28' },
    ],
  },
  {
    id: 'nrt-4',
    name: 'מסעדת "פרנצ׳סקה" — ראש פינה',
    city: 'ראש פינה',
    region: 'north',
    category: 'restaurant',
    vibe: 'מסעדת שף ב"ראש פינה העתיקה" עם נוף לכנרת. ריהוט וינטאג׳, אוכל ים תיכוני ואווירה חלומית.',
    address: 'ראש פינה העתיקה, ראש פינה',
    googleMapsUrl: 'https://maps.google.com/?q=Rosh+Pinna+Old+Quarter',
    kosher: false,
    priceRange: '₪₪',
    averageRating: 4.8,
    reviewCount: 2,
    reviews: [
      { id: 'r28', authorName: 'ה.כ', rating: 5, text: 'ראש פינה + שקיעה + אוכל מעולה. מה עוד צריך?', createdAt: '2026-03-19' },
      { id: 'r29', authorName: 'ל.ר', rating: 5, text: 'אחד הדייטים הכי טובים שהיה לנו. בזכות המקום.', createdAt: '2026-02-07' },
    ],
  },

  // ── South ─────────────────────────────────────────────────────────────────

  {
    id: 'sth-1',
    name: 'גן לאומי עין גדי',
    city: 'עין גדי',
    region: 'south',
    category: 'park',
    vibe: 'שמורת טבע עם מפלים, נחלים ועיזים קבאלים. הליכה בטבע — חוויה אחרת לחלוטין.',
    address: 'שמורת עין גדי, מדבר יהודה',
    googleMapsUrl: 'https://maps.google.com/?q=Ein+Gedi+Nature+Reserve',
    priceRange: '₪',
    averageRating: 4.8,
    reviewCount: 3,
    reviews: [
      { id: 'r30', authorName: 'ת.מ', rating: 5, text: 'שוחים יחד מתחת למפל — לא שוכחים!', createdAt: '2026-03-30' },
      { id: 'r31', authorName: 'ז.ב', rating: 5, text: 'הטבע מדהים. מגיעים עם נעליים נוחות.', createdAt: '2026-02-25' },
      { id: 'r32', authorName: 'פ.ל', rating: 5, text: 'אחד הדברים הכי יפים שעשינו ביחד.', createdAt: '2026-01-10' },
    ],
  },
  {
    id: 'sth-2',
    name: 'מלון ים המלח — SPA לובי',
    city: 'ים המלח',
    region: 'south',
    category: 'hotel_lobby',
    vibe: 'לובי ספא יוקרתי עם נוף לים המלח. אווירה מרגיעה ורומנטית. מושלם לפגישה ב"אמצע הארץ".',
    address: 'אזור מלונות ים המלח',
    googleMapsUrl: 'https://maps.google.com/?q=Dead+Sea+Hotels',
    kosher: true,
    priceRange: '₪₪₪',
    averageRating: 4.6,
    reviewCount: 2,
    reviews: [
      { id: 'r33', authorName: 'ש.א', rating: 5, text: 'הנוף לים המלח פשוט אחר. רגוע ומיוחד.', createdAt: '2026-03-11' },
      { id: 'r34', authorName: 'א.ל', rating: 4, text: 'יקר אבל החוויה שווה. הלכנו לשחות אח"כ!', createdAt: '2026-02-03' },
    ],
  },
  {
    id: 'sth-3',
    name: 'מסעדת "לה מאר" — אילת',
    city: 'אילת',
    region: 'south',
    category: 'restaurant',
    vibe: 'מסעדת דגים על קו החוף של אילת. ים אדום, דגי אקווריום ושקיעה. פנטסטי לדייט מיוחד.',
    address: 'טיילת אילת',
    googleMapsUrl: 'https://maps.google.com/?q=Eilat+Promenade+Restaurant',
    kosher: false,
    priceRange: '₪₪',
    averageRating: 4.5,
    reviewCount: 2,
    reviews: [
      { id: 'r35', authorName: 'ו.כ', rating: 5, text: 'אוכל טרי, ים אדום מבחוץ — ציפור ב"יד!', createdAt: '2026-03-27' },
      { id: 'r36', authorName: 'י.ס', rating: 4, text: 'יפה ומרשים. צריך להזמין מקום מראש.', createdAt: '2026-02-12' },
    ],
  },
  {
    id: 'sth-4',
    name: 'פארק גן הנחל — באר שבע',
    city: 'באר שבע',
    region: 'south',
    category: 'quiet',
    vibe: 'פארק עירוני נחמד בבאר שבע. שקט, ירוק, ומתאים לטיול ספונטני בין שיחות.',
    address: 'גן הנחל, באר שבע',
    googleMapsUrl: 'https://maps.google.com/?q=Nahal+Park+Beer+Sheva',
    priceRange: '₪',
    averageRating: 4.1,
    reviewCount: 2,
    reviews: [
      { id: 'r37', authorName: 'כ.ג', rating: 4, text: 'פארק נחמד ושקט. מומלץ לפגישה ראשונה נינוחה.', createdAt: '2026-03-06' },
      { id: 'r38', authorName: 'ל.ח', rating: 4, text: 'פחות מרשים מצפון, אבל ממש נחמד לדרום.', createdAt: '2026-01-25' },
    ],
  },
]
