import type { FemaleProfile, MaleProfile } from '@/types/registration'

const now = Date.now()
const days = (n: number) => new Date(now - n * 24 * 60 * 60 * 1000)

// ─── Female Mock Profiles ─────────────────────────────────────────────────────

export const MOCK_FEMALE_PROFILE: FemaleProfile = {
  id: 'f1',
  firstName: 'רחל',
  lastName: 'כהן',
  age: 24,
  hebrewBirthday: 'כ"ג תשרי תשפ"ד',
  status: 'single',
  community: 'ירושלים – דתי לאומי',
  occupation: 'מורה',
  city: 'ירושלים',
  phone: '0521234567',
  email: 'rachel@example.com',
  photos: [],
  style: 'modern',
  partnerStyle: 'open',
  preferredStream: '',
  traits: ['calm', 'serious', 'communicative'],
  relationshipValues: ['stability', 'family', 'depth'],
  brings: ['stability', 'commitment', 'communication'],
  doesntSuit: '',
  flexibility: 'important',
  clothing: 'classic',
  headcovering: 'kerchief_only',
  partnerClothing: 'bw_elegant',
  phoneType: 'filtered',
  aboutMe: 'אני מורה לאמנות בבית ספר יסודי בירושלים, בחורה רצינית עם לב פתוח ואהבת אנשים. בזמני הפנוי אני אוהבת לצייר, לקרוא ולהתפתח. מאמינה שחיים טובים בנויים על אמת, תקשורת ואמונה פשוטה וחמה.',
  aboutPartner: 'מחפשת בחור עם ראש פתוח ולב גדול, שמחויב לחיים יהודיים אך לא נוקשה. חשוב לי שיהיה תקשורתי ויודע להקשיב. בחור שיש לו יציבות ואחריות, אבל גם יכולת לשמוח ולהיות קל לב.',
  matchmakerStatus: 'orange',
  notes: [
    { id: 'n1', author: 'שרה מ.', text: 'פגישה ראשונה – רושם חיובי מאוד, בחורה רצינית ומוכנה.', createdAt: new Date('2024-11-15T10:30:00') },
    { id: 'n2', author: 'מרים כ.', text: 'מומלצת בחום על ידי הרב שלמה לוי.', createdAt: new Date('2024-11-20T14:00:00') },
  ],
  lockedAt: null,
  lastOfferDate: days(2),
}

export const MOCK_FEMALE_PROFILES: FemaleProfile[] = [
  MOCK_FEMALE_PROFILE,
  {
    id: 'f2',
    firstName: 'מרים',
    lastName: 'לוי',
    age: 26,
    hebrewBirthday: 'ט׳ אדר תשפ"ב',
    status: 'single',
    community: 'תל אביב – מסורתי',
    occupation: 'אחות',
    city: 'תל אביב',
    phone: '0534567890',
    email: 'miriam@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['happy', 'social', 'proactive'],
    relationshipValues: ['emotional', 'lightness', 'family'],
    brings: ['lightness', 'communication', 'homey'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'stylish',
    headcovering: 'wig_only',
    partnerClothing: 'colorful_weekday',
    phoneType: 'smartphone',
    aboutMe: 'אחות מוסמכת עובדת בבית חולים, בחורה חיה ושמחה שאוהבת לפגוש אנשים ולעזור. חיה את החיים בסגנון מעשי ולא מסבכת דברים. אוהבת טיולים, מוזיקה טובה וארוחות משפחתיות שוקקות.',
    aboutPartner: 'מחפשת בחור חי ושמח, שאוהב אנשים ולא נסגר בתוך עצמו. מישהו שיש לו כיוון בחיים אבל שיודע גם לצחוק ולהנות. לא חייב להיות ישיבתי, חשוב שיהיה ישר ונורמלי.',
    matchmakerStatus: 'light_red',
    notes: [
      { id: 'n3', author: 'רות ב.', text: 'הכירה שידוך בחודש שעבר, לא יצא לפועל. ממשיכים לחפש.', createdAt: new Date('2024-10-05T09:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(25),
  },
  {
    id: 'f3',
    firstName: 'שרה',
    lastName: 'גרוס',
    age: 22,
    hebrewBirthday: 'ב׳ ניסן תשפ"ה',
    status: 'single',
    community: 'בני ברק – חרדי',
    occupation: 'סטודנטית',
    city: 'בני ברק',
    phone: '0521112222',
    email: 'sara@example.com',
    photos: [],
    style: 'shmura',
    partnerStyle: 'shmur',
    preferredStream: 'ליטאי',
    traits: ['serious', 'deep', 'calm'],
    relationshipValues: ['spiritual', 'worldview', 'depth'],
    brings: ['commitment', 'reliability', 'depth'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'very_simple',
    headcovering: 'wig_no_cut',
    partnerClothing: 'only_bw',
    phoneType: 'kosher',
    aboutMe: 'סטודנטית בחינוך בבני ברק, בחורה שקטה ועמוקה שמחפשת משמעות אמיתית בחיים. מחויבת לאורח חיים תורני בכל תחומי החיים. גדלתי בבית ליטאי ואני שואפת לבנות בית כזה.',
    aboutPartner: 'מחפשת בחור ישיבה שמחויב לתורה ולמדות, בעל אופי שקט ויציב. חשוב לי שיהיה ירא שמים אמיתי ולא רק למראית עיין. בחור עמוק שיש לו עולם פנימי עשיר.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(75),
  },
  {
    id: 'f4',
    firstName: 'דבורה',
    lastName: 'פרידמן',
    age: 28,
    hebrewBirthday: 'י"ח חשון תשפ"ג',
    status: 'divorced',
    hasChildren: true,
    numberOfChildren: 2,
    community: 'רמת גן – ספרדי',
    occupation: 'עורכת דין',
    city: 'רמת גן',
    phone: '0503334444',
    email: 'devora@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['proactive', 'communicative', 'deep'],
    relationshipValues: ['stability', 'aspirations', 'emotional'],
    brings: ['responsibility', 'stability', 'communication'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'respectable',
    headcovering: 'wig_plus_cover',
    partnerClothing: 'bw_elegant',
    phoneType: 'filtered',
    aboutMe: 'עורכת דין פעילה ברמת גן, גרושה שמחפשת להתחיל פרק חדש. אישה עצמאית, רצינית ומחויבת, שגדלה בקהילה ספרדית מסורתית. מאמינה בחיי משפחה יציבים המבוססים על כבוד הדדי.',
    aboutPartner: 'מחפשת גבר בוגר, מחויב ויציב שעברו חינוך לקחת אחריות. חשוב שיהיה מסורתי-פלוס – כיבוד דת אבל לא קיצוני. אדם שמסוגל לבנות שותפות אמיתית.',
    matchmakerStatus: 'green',
    notes: [
      { id: 'n4', author: 'חנה ש.', text: 'שידוך פעיל עם יוסף מ. – בשלב הבירורים.', createdAt: new Date('2025-01-10T11:00:00') },
    ],
    lockedAt: days(-2 / 24),
    lockedBy: 'שדכן א',
    lastOfferDate: days(5),
  },
  {
    id: 'f5',
    firstName: 'לאה',
    lastName: 'שפירא',
    age: 25,
    hebrewBirthday: 'כ"ה תמוז תשפ"ד',
    status: 'single',
    community: 'חיפה – דתי לאומי',
    occupation: 'מהנדסת',
    city: 'חיפה',
    phone: '0525556666',
    email: 'leah@example.com',
    photos: [],
    style: 'modern',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['flowing', 'happy', 'social'],
    relationshipValues: ['family', 'lightness', 'emotional'],
    brings: ['lightness', 'homey', 'reliability'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'modern',
    headcovering: 'no_preference',
    partnerClothing: 'very_modern',
    phoneType: 'smartphone',
    aboutMe: 'מהנדסת תוכנה בחברת הייטק בחיפה, שוחרת חופש ויצירתיות. חיה את החיים בשמחה ובקלילות, אוהבת לטייל ולנסות דברים חדשים. שומרת שבת ומסורת יהודית מתוך בחירה ואהבה.',
    aboutPartner: 'מחפשת בחור שמח ופתוח לחיים שלא "כבה" בתקיפות. אוהב לטייל וגם עם ראש בעסקים. לא מחפשת ישיבתי – חשוב שיהיה ישר, מאמין וחי את החיים בשלמות.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: null,
  },
  {
    id: 'f6',
    firstName: 'נעמי',
    lastName: 'ברגר',
    age: 23,
    hebrewBirthday: 'י"א שבט תשפ"ה',
    status: 'single',
    community: 'מודיעין – דתי לאומי',
    occupation: 'פיזיותרפיסטית',
    city: 'מודיעין',
    phone: '0527771111',
    email: 'naomi@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['calm', 'social', 'communicative'],
    relationshipValues: ['family', 'stability', 'emotional'],
    brings: ['homey', 'reliability', 'communication'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'classic',
    headcovering: 'kerchief_only',
    partnerClothing: 'colorful_weekday',
    phoneType: 'filtered',
    aboutMe: 'פיזיותרפיסטית צעירה במרפאה פרטית, בחורה חמה ומטפחת שמאמינה בכוח הקשר האנושי. אוהבת בישול, טיולים בטבע ומפגשים עם משפחה.',
    aboutPartner: 'מחפשת בחור שמח ושמאמין בחיים טובים, בעל ראש מסודר ולב פתוח. חשוב לי שיהיה מחויב לחיים יהודיים ואוהב משפחה.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'n6', author: 'שדכן א', text: 'מועמדת מצוינת – בשלב בירורים עם שני צדדים.', createdAt: new Date('2025-02-01T10:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(6),
  },
  {
    id: 'f7',
    firstName: 'תמר',
    lastName: 'אלון',
    age: 27,
    hebrewBirthday: 'כ׳ סיון תשפ"ב',
    status: 'single',
    community: 'באר שבע – ספרדי מסורתי',
    occupation: 'רואת חשבון',
    city: 'באר שבע',
    phone: '0508882222',
    email: 'tamar@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['proactive', 'serious', 'deep'],
    relationshipValues: ['aspirations', 'stability', 'depth'],
    brings: ['responsibility', 'stability', 'depth'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'respectable',
    headcovering: 'wig_with_cut',
    partnerClothing: 'bw_elegant',
    phoneType: 'filtered',
    aboutMe: 'רואת חשבון בחברה פיננסית, בחורה שאפתנית ומסודרת שמוצאת שמחה גם בדברים הקטנים. גדלתי בבית ספרדי מסורתי עם ערכי משפחה חזקים.',
    aboutPartner: 'מחפשת גבר עם יציבות מקצועית ואישית, שיש לו מטרות ברורות. חשוב שיהיה מכבד מסורת ואוהב משפחה.',
    matchmakerStatus: 'light_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(35),
  },
  {
    id: 'f8',
    firstName: 'אסתר',
    lastName: 'שמש',
    age: 21,
    hebrewBirthday: 'ה׳ אלול תשפ"ו',
    status: 'single',
    community: 'ירושלים – חסידי',
    occupation: 'גננת',
    city: 'ירושלים',
    phone: '0521113333',
    email: 'esther@example.com',
    photos: [],
    style: 'shmura',
    partnerStyle: 'shmur',
    preferredStream: 'חסידי',
    traits: ['calm', 'shy', 'deep'],
    relationshipValues: ['spiritual', 'family', 'stability'],
    brings: ['homey', 'commitment', 'reliability'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'very_simple',
    headcovering: 'wig_no_cut',
    partnerClothing: 'only_bw',
    phoneType: 'kosher',
    aboutMe: 'גננת בגן חרדי, בחורה ביישנית ועמוקה שאוהבת ילדים ובניית בית. חיה מתוך אמונה ושמחה פנימית שקטה.',
    aboutPartner: 'מחפשת בחור ירא שמים וצנוע, שמעריך שקט ועומק. חסידי-מסורתי שרוצה לבנות בית ביראת שמים.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(90),
  },
  {
    id: 'f9',
    firstName: 'חנה',
    lastName: 'זילברמן',
    age: 29,
    hebrewBirthday: 'י"ג תמוז תשפ"א',
    status: 'divorced',
    hasChildren: false,
    community: 'פתח תקווה – ספרדי',
    occupation: 'מנהלת חשבונות',
    city: 'פתח תקווה',
    phone: '0529994444',
    email: 'hana@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['proactive', 'communicative', 'social'],
    relationshipValues: ['family', 'emotional', 'stability'],
    brings: ['communication', 'homey', 'responsibility'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'stylish',
    headcovering: 'wig_only',
    partnerClothing: 'colorful_weekday',
    phoneType: 'smartphone',
    aboutMe: 'מנהלת חשבונות מנוסה, גרושה שמחפשת התחלה חדשה. אישה חמה ומשפחתית עם המון אהבה לתת. מסורתית-פלוס עם ערכים ברורים.',
    aboutPartner: 'מחפשת גבר בוגר, מסורתי ואחראי שמוכן לבנות בית עם אישה שיש לה ניסיון. חשוב שיהיה ישר ואמין.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'n9', author: 'שדכן ב', text: 'שיחה ראשונית – חיובי. ממתינה לתשובה.', createdAt: new Date('2025-03-05T09:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(4),
  },
  {
    id: 'f10',
    firstName: 'רבקה',
    lastName: 'נחמני',
    age: 24,
    hebrewBirthday: 'כ"ב חשון תשפ"ד',
    status: 'single',
    community: 'נתניה – מסורתי',
    occupation: 'מעצבת גרפית',
    city: 'נתניה',
    phone: '0505555555',
    email: 'rivka@example.com',
    photos: [],
    style: 'modern',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['flowing', 'happy', 'proactive'],
    relationshipValues: ['lightness', 'aspirations', 'family'],
    brings: ['lightness', 'depth', 'communication'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'modern',
    headcovering: 'no_preference',
    partnerClothing: 'very_modern',
    phoneType: 'smartphone',
    aboutMe: 'מעצבת גרפית עצמאית בנתניה, יצירתית ואוהבת אמנות. שומרת שבת ומסורת יהודית בשמחה. חיה את החיים עם שמחה ויצירתיות.',
    aboutPartner: 'מחפשת בחור פתוח, יצירתי ועם חוש הומור. לא חייב להיות ישיבתי – חשוב שיהיה אמיתי ועם ערכים.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: null,
  },
  {
    id: 'f11',
    firstName: 'ציפורה',
    lastName: 'האוזר',
    age: 23,
    hebrewBirthday: 'ג׳ כסלו תשפ"ה',
    status: 'single',
    community: 'בני ברק – ליטאי',
    occupation: 'מורה',
    city: 'בני ברק',
    phone: '0521116666',
    email: 'tzipora@example.com',
    photos: [],
    style: 'shmura',
    partnerStyle: 'shmur',
    preferredStream: 'ליטאי',
    traits: ['serious', 'calm', 'deep'],
    relationshipValues: ['spiritual', 'worldview', 'stability'],
    brings: ['commitment', 'reliability', 'depth'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'very_simple',
    headcovering: 'wig_no_cut',
    partnerClothing: 'only_bw',
    phoneType: 'kosher',
    aboutMe: 'מורה לחינוך מיוחד בבני ברק, בחורה עמוקה ומוסרית שרואה בחינוך שליחות. מחויבת לאורח חיים תורני.',
    aboutPartner: 'מחפשת בחור ישיבה מחויב, עמוק וירא שמים. חשוב שיהיה ליטאי בסגנון ובהשקפה.',
    matchmakerStatus: 'light_red',
    notes: [
      { id: 'n11', author: 'שדכן ג', text: 'הצעה ראשונה נשלחה לפני חודש – ממתינים.', createdAt: new Date('2025-01-20T08:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(30),
  },
  {
    id: 'f12',
    firstName: 'יעל',
    lastName: 'מרקוס',
    age: 26,
    hebrewBirthday: 'י"ז שבט תשפ"ג',
    status: 'single',
    community: 'רעננה – דתי לאומי',
    occupation: 'עובדת סוציאלית',
    city: 'רעננה',
    phone: '0527778888',
    email: 'yael@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['communicative', 'social', 'deep'],
    relationshipValues: ['emotional', 'family', 'depth'],
    brings: ['communication', 'homey', 'depth'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'classic',
    headcovering: 'kerchief_only',
    partnerClothing: 'bw_elegant',
    phoneType: 'filtered',
    aboutMe: 'עובדת סוציאלית ברשות מקומית ברעננה, בחורה אמפתית ומקשיבה שמוצאת משמעות בעזרה לאחרים. גדלתי בבית דתי-לאומי פתוח.',
    aboutPartner: 'מחפשת בחור בעל לב גדול, שמסוגל לשיחה עמוקה ואוהב אנשים. חשוב שיהיה מחויב לחיים יהודיים ואוהב לתת.',
    matchmakerStatus: 'orange',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(7),
  },
  {
    id: 'f13',
    firstName: 'שיר',
    lastName: 'אבידן',
    age: 25,
    hebrewBirthday: 'כ"ט אייר תשפ"ד',
    status: 'single',
    community: 'כפר סבא – מסורתי',
    occupation: 'מדריכת כושר',
    city: 'כפר סבא',
    phone: '0526669999',
    email: 'shir@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['happy', 'proactive', 'social'],
    relationshipValues: ['lightness', 'family', 'emotional'],
    brings: ['lightness', 'homey', 'reliability'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'stylish',
    headcovering: 'no_preference',
    partnerClothing: 'very_modern',
    phoneType: 'smartphone',
    aboutMe: 'מדריכת כושר ופילאטיס, בחורה אנרגטית ושמחה שמאמינה בחיים בריאים ומאוזנים. שומרת שבת ומסורת ממקום של בחירה.',
    aboutPartner: 'מחפשת בחור פעיל ושמח, שאוהב חיים ולא נסגר. חשוב שיהיה ישר ואמיתי, עם ערכים ואהבת משפחה.',
    matchmakerStatus: 'light_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(45),
  },
  {
    id: 'f14',
    firstName: 'אביגיל',
    lastName: 'שטיין',
    age: 22,
    hebrewBirthday: 'ב׳ טבת תשפ"ו',
    status: 'single',
    community: 'אשדוד – ספרדי חרדי',
    occupation: 'סטודנטית',
    city: 'אשדוד',
    phone: '0508883333',
    email: 'abigail@example.com',
    photos: [],
    style: 'shmura',
    partnerStyle: 'shmur',
    preferredStream: 'ספרדי',
    traits: ['calm', 'serious', 'shy'],
    relationshipValues: ['spiritual', 'family', 'stability'],
    brings: ['homey', 'commitment', 'reliability'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'very_simple',
    headcovering: 'wig_no_cut',
    partnerClothing: 'only_bw',
    phoneType: 'kosher',
    aboutMe: 'סטודנטית לחינוך, גדלתי בבית ספרדי-חרדי בחיפה. בחורה צנועה ויראת שמים שמחפשת להקים בית כשר ושלם.',
    aboutPartner: 'מחפשת בחור ישיבה ספרדי, ירא שמים ומכבד הורים. חשוב שיהיה עם עתיד ברור ורצון להקים בית.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(120),
  },
  {
    id: 'f15',
    firstName: 'נורית',
    lastName: 'גולן',
    age: 30,
    hebrewBirthday: 'כ"ד ניסן תשפ"ט',
    status: 'divorced',
    community: 'ראשון לציון – מסורתי',
    occupation: 'מנהלת שיווק',
    city: 'ראשון לציון',
    phone: '0524441111',
    email: 'nurit@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['proactive', 'communicative', 'happy'],
    relationshipValues: ['aspirations', 'family', 'emotional'],
    brings: ['responsibility', 'lightness', 'communication'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'modern',
    headcovering: 'wig_with_cut',
    partnerClothing: 'colorful_weekday',
    phoneType: 'smartphone',
    aboutMe: 'מנהלת שיווק בחברה גדולה, גרושה עם ילד קטן. אישה חזקה ומאמינה שיודעת מה היא רוצה מהחיים. מסורתית, חמה ואוהבת אנשים.',
    aboutPartner: 'מחפשת גבר בוגר שמקבל את מצבי ורוצה לבנות בית חדש. חשוב שיהיה בשל, מסורתי ועם לב פתוח.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'n15', author: 'שדכן ב', text: 'שיחה טובה – מוכנה ובשלה. להמשיך לבדוק.', createdAt: new Date('2025-03-10T14:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(5),
  },
]

// ─── Male Mock Profiles ───────────────────────────────────────────────────────

export const MOCK_MALE_PROFILES: MaleProfile[] = [
  {
    id: 'm1',
    firstName: 'יעקב',
    lastName: 'כהן',
    age: 25,
    hebrewBirthday: 'ז׳ אייר תשפ"ד',
    status: 'single',
    community: 'ירושלים – דתי לאומי',
    occupation: 'בעל מקצוע',
    city: 'ירושלים',
    phone: '0521230001',
    email: 'yaakov@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['calm', 'proactive', 'communicative'],
    relationshipValues: ['stability', 'family', 'depth'],
    brings: ['commitment', 'responsibility', 'stability'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'wig_any',
    phoneType: 'filtered',
    aboutMe: 'בעל מקצוע (חשמלאי) בירושלים, בחור ישר ופועל ידיים שגאה בעבודתו. קיים שבת וחגים, מתפלל בבוקר, ועולם התורה קרוב לליבי גם אם איני אוחז בחינוך ישיבתי. אוהב ספורט, טבע ומשפחה.',
    aboutPartner: 'מחפש בחורה פשוטה ויציבה שמחפשת בית ומשפחה. לא צריכה להיות אינטלקטואלית מאוד, אבל חשוב שתהיה ישרה, מחויבת ובעלת אופי חם עם מחויבות לשמירת מצוות.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'nm1', author: 'שמואל ט.', text: 'הצעה נשלחה אתמול, מחכים לתשובה.', createdAt: new Date('2025-01-12T08:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(3),
  },
  {
    id: 'm2',
    firstName: 'אברהם',
    lastName: 'לוי',
    age: 27,
    hebrewBirthday: 'כ׳ שבט תשפ"א',
    status: 'single',
    community: 'תל אביב – מסורתי',
    occupation: 'מתכנת',
    city: 'תל אביב',
    phone: '0534560002',
    email: 'avraham@example.com',
    photos: [],
    style: 'modern',
    partnerStyle: 'modern',
    preferredStream: '',
    traits: ['deep', 'serious', 'flowing'],
    relationshipValues: ['aspirations', 'worldview', 'emotional'],
    brings: ['depth', 'communication', 'reliability'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'always_colorful',
    partnerClothing: 'kerchief',
    phoneType: 'smartphone',
    aboutMe: 'מתכנת Full Stack בסטארטאפ תל אביבי, אינטלקטואל שאוהב ספרות, פילוסופיה ומוזיקה קלאסית. שומר שבת בשמחה ומאמין שיהדות ומודרניות יכולות לדור בכפיפה אחת.',
    aboutPartner: 'מחפש בחורה עם עולם פנימי עשיר, שמסוגלת לנהל שיחה עמוקה. חשוב לי שתהיה עצמאית, חושבת, ועם חיבור אמיתי לזהות יהודית. לא חייבת להיות שומרת שבת קפדנית.',
    matchmakerStatus: 'light_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(20),
  },
  {
    id: 'm3',
    firstName: 'יוסף',
    lastName: 'גרוס',
    age: 23,
    hebrewBirthday: 'ג׳ אלול תשפ"ה',
    status: 'single',
    community: 'בני ברק – חרדי',
    occupation: 'בחור ישיבה',
    city: 'בני ברק',
    phone: '0521110003',
    email: 'yosef@example.com',
    photos: [],
    style: 'yeshivish',
    partnerStyle: 'closed',
    preferredStream: 'ליטאי',
    traits: ['serious', 'deep', 'shy'],
    relationshipValues: ['spiritual', 'worldview', 'stability'],
    brings: ['commitment', 'depth', 'reliability'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'only_bw',
    partnerClothing: 'wig_only',
    phoneType: 'kosher',
    aboutMe: 'בחור ישיבה מבני ברק, מחויב לתורה ולמדות בכל כוחי. גדלתי בבית ליטאי ורוצה לבנות בית עם יסודות חזקים. לא קיצוני אבל הרצינות היא הערך שמנחה אותי.',
    aboutPartner: 'מחפש בחורה שמורה, ירת שמים ועם ענווה. בחורה שמבינה שבית יהודי אמיתי נבנה לאט. חשוב שתהיה צנועה בלבושה ובהתנהגותה ומחויבת לאורח חיים תורני.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(90),
  },
  {
    id: 'm4',
    firstName: 'דוד',
    lastName: 'פרידמן',
    age: 29,
    hebrewBirthday: 'כ"ד כסלו תשפ"ב',
    status: 'divorced',
    hasChildren: true,
    numberOfChildren: 1,
    community: 'רמת גן – ספרדי',
    occupation: 'רואה חשבון',
    city: 'רמת גן',
    phone: '0503330004',
    email: 'david@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['social', 'proactive', 'happy'],
    relationshipValues: ['family', 'homey', 'emotional'],
    brings: ['stability', 'homey', 'communication'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'modern_modest',
    phoneType: 'filtered',
    aboutMe: 'רואה חשבון ברמת גן, גרוש ומחפש התחלה חדשה. ספרדי מסורתי שגדל עם ערכי משפחה ואמונה. בעל ראש פרקטי, אוהב לארגן ולתכנן, אבל גם יודע לחגוג ולפנק.',
    aboutPartner: 'מחפש אישה בוגרת ורצינית שמוכנה לבנות ביחד. חשוב שתהיה חמה ומשפחתית עם ערכים מסורתיים. כיבוד שבת וחג צריך להיות טבעי עבורה.',
    matchmakerStatus: 'green',
    notes: [
      { id: 'nm2', author: 'בנימין כ.', text: 'שידוך פעיל עם דבורה פ. – בשלב הבירורים.', createdAt: new Date('2025-01-10T11:00:00') },
    ],
    lockedAt: new Date(now - 10 * 60 * 60 * 1000),
    lockedBy: 'שדכן א',
    lastOfferDate: days(6),
  },
  {
    id: 'm5',
    firstName: 'משה',
    lastName: 'שפירא',
    age: 24,
    hebrewBirthday: 'ט"ו אב תשפ"ד',
    status: 'single',
    community: 'חיפה – דתי לאומי',
    occupation: 'סטודנט',
    city: 'חיפה',
    phone: '0525550005',
    email: 'moshe@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['flowing', 'calm', 'communicative'],
    relationshipValues: ['lightness', 'family', 'stability'],
    brings: ['lightness', 'reliability', 'homey'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'colorful_weekday',
    partnerClothing: 'no_preference',
    phoneType: 'filtered',
    aboutMe: 'סטודנט להנדסה אזרחית בטכניון, זורם ואופטימי בטבעי. גדלתי בחיפה בבית דתי-לאומי פתוח ומחבק. אוהב טיולים, מוזיקה וחברים, ובמקביל שומר תפילה ושבת כחלק מחיי.',
    aboutPartner: 'מחפש בחורה שמחה ורגועה, שחיה את החיים בפשטות ובשמחה. לא חשוב לי שתהיה ישיבתית – חשוב שתהיה אמיתית ועם ערכים. בחורה שמחפשת לבנות בית ומוכנה לצמוח ביחד.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: null,
  },
  {
    id: 'm6',
    firstName: 'אלי',
    lastName: 'ברנשטיין',
    age: 26,
    hebrewBirthday: 'ט׳ תשרי תשפ"ג',
    status: 'single',
    community: 'מודיעין – דתי לאומי',
    occupation: 'מהנדס תוכנה',
    city: 'מודיעין',
    phone: '0527770006',
    email: 'eli@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['calm', 'deep', 'communicative'],
    relationshipValues: ['stability', 'depth', 'worldview'],
    brings: ['reliability', 'depth', 'commitment'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'wig_any',
    phoneType: 'filtered',
    aboutMe: 'מהנדס תוכנה בחברת הייטק במודיעין, בחור מסודר ואינטלקטואל שמאמין שטכנולוגיה ויהדות יכולות להתקיים בהרמוניה. שומר שבת ומתפלל, אוהב לקרוא ולהתפתח.',
    aboutPartner: 'מחפש בחורה חכמה ועמוקה, עם ערכים ברורים וחיבור אמיתי ליהדות. חשוב שתהיה תקשורתית ואוהבת לצמוח.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'nm6', author: 'שדכן א', text: 'מועמד מצוין – בשלב בירורים ראשוני.', createdAt: new Date('2025-02-15T10:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(5),
  },
  {
    id: 'm7',
    firstName: 'שמואל',
    lastName: 'רוזנברג',
    age: 22,
    hebrewBirthday: 'י"ד אדר תשפ"ו',
    status: 'single',
    community: 'בני ברק – חסידי',
    occupation: 'בחור ישיבה',
    city: 'בני ברק',
    phone: '0521110007',
    email: 'shmuel@example.com',
    photos: [],
    style: 'yeshivish',
    partnerStyle: 'closed',
    preferredStream: 'חסידי',
    traits: ['shy', 'serious', 'deep'],
    relationshipValues: ['spiritual', 'worldview', 'depth'],
    brings: ['commitment', 'depth', 'homey'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'only_bw',
    partnerClothing: 'wig_only',
    phoneType: 'kosher',
    aboutMe: 'בחור ישיבה חסידי, לומד ומתפתח בעולם התורה. ביישן בטבעו אבל עם עולם פנימי עשיר. שואף לבנות בית של יראת שמים ושלום בית.',
    aboutPartner: 'מחפש בחורה חסידית, צנועה וירת שמים. בחורה עם לב טוב וביישנות יפה.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(95),
  },
  {
    id: 'm8',
    firstName: 'ניר',
    lastName: 'אוחיון',
    age: 28,
    hebrewBirthday: 'כ"ב תשרי תשפ"ב',
    status: 'single',
    community: 'אשדוד – ספרדי מסורתי',
    occupation: 'מורה לספורט',
    city: 'אשדוד',
    phone: '0508880008',
    email: 'nir@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['social', 'happy', 'proactive'],
    relationshipValues: ['family', 'lightness', 'emotional'],
    brings: ['lightness', 'homey', 'stability'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'colorful_weekday',
    partnerClothing: 'modern_modest',
    phoneType: 'smartphone',
    aboutMe: 'מורה לחינוך גופני בתיכון באשדוד, ספרדי מסורתי שאוהב ספורט, ים ומשפחה. חי את החיים בשמחה ובחיוביות.',
    aboutPartner: 'מחפש בחורה שמחה ואנרגטית, שאוהבת חיים ומשפחה. חשוב שתהיה מסורתית ואוהבת בנות ובנים.',
    matchmakerStatus: 'light_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(40),
  },
  {
    id: 'm9',
    firstName: 'אורי',
    lastName: 'לוינגר',
    age: 26,
    hebrewBirthday: 'ה׳ אב תשפ"ג',
    status: 'single',
    community: 'ירושלים – חרדי לאומי',
    occupation: 'עורך דין',
    city: 'ירושלים',
    phone: '0527770009',
    email: 'uri@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: 'ציוני-דתי',
    traits: ['proactive', 'serious', 'communicative'],
    relationshipValues: ['aspirations', 'stability', 'worldview'],
    brings: ['responsibility', 'commitment', 'stability'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'black_kippah',
    partnerClothing: 'wig_kerchief',
    phoneType: 'filtered',
    aboutMe: 'עורך דין בירושלים, בחור שאפתן ומחויב הן לקריירה הן לחיים יהודיים. אוהב לימוד תורה בסוף שבת ושיח אינטלקטואלי.',
    aboutPartner: 'מחפש בחורה שאפתנית ומחויבת, עם עולם פנימי. חשוב שתהיה ציונית-דתית עם ראש פתוח.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'nm9', author: 'שדכן ב', text: 'שיחה טובה – ממשיכים לבדוק.', createdAt: new Date('2025-03-01T09:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(3),
  },
  {
    id: 'm10',
    firstName: 'בנימין',
    lastName: 'כץ',
    age: 30,
    hebrewBirthday: 'י׳ שבט תשפ"ט',
    status: 'divorced',
    hasChildren: false,
    community: 'פתח תקווה – ספרדי',
    occupation: 'מנהל מכירות',
    city: 'פתח תקווה',
    phone: '0509990010',
    email: 'binyamin@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['social', 'communicative', 'proactive'],
    relationshipValues: ['family', 'emotional', 'stability'],
    brings: ['stability', 'communication', 'homey'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'modern_modest',
    phoneType: 'filtered',
    aboutMe: 'מנהל מכירות מנוסה בחברת נדל"ן, גרוש שמחפש התחלה חדשה ורצינית. ספרדי מסורתי עם ערכי משפחה חזקים. אוהב לחגוג שבת ולארח.',
    aboutPartner: 'מחפש אישה בוגרת ומשפחתית, שמקבלת את עברי ורוצה לבנות ביחד. חשוב שתהיה חמה, מסורתית ואמינה.',
    matchmakerStatus: 'light_red',
    notes: [
      { id: 'nm10', author: 'שדכן ג', text: 'הצעה נשלחה לפני 3 שבועות – ממתינים לתשובה.', createdAt: new Date('2025-02-20T11:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(22),
  },
  {
    id: 'm11',
    firstName: 'גיא',
    lastName: 'מזרחי',
    age: 24,
    hebrewBirthday: 'כ"ח ניסן תשפ"ד',
    status: 'single',
    community: 'ראשון לציון – מסורתי',
    occupation: 'טכנאי מחשבים',
    city: 'ראשון לציון',
    phone: '0524440011',
    email: 'guy@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['flowing', 'happy', 'calm'],
    relationshipValues: ['lightness', 'family', 'homey'],
    brings: ['lightness', 'reliability', 'homey'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'colorful_weekday',
    partnerClothing: 'no_preference',
    phoneType: 'smartphone',
    aboutMe: 'טכנאי מחשבים עצמאי, בחור נעים ופשוט שחי את החיים בזרימה. שומר שבת ומסורת מתוך בחירה וחיבה. אוהב ים, מוזיקה ישראלית וארוחות עם חברים.',
    aboutPartner: 'מחפש בחורה פשוטה ושמחה, שאוהבת חיים ולא מסבכת. חשוב שתהיה ישרה ואוהבת משפחה.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: null,
  },
  {
    id: 'm12',
    firstName: 'אריאל',
    lastName: 'פינקלשטיין',
    age: 25,
    hebrewBirthday: 'י"א חשון תשפ"ד',
    status: 'single',
    community: 'ירושלים – דתי לאומי',
    occupation: 'רופא מתמחה',
    city: 'ירושלים',
    phone: '0527770012',
    email: 'ariel@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['serious', 'deep', 'communicative'],
    relationshipValues: ['aspirations', 'depth', 'stability'],
    brings: ['reliability', 'commitment', 'depth'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'black_kippah',
    partnerClothing: 'wig_any',
    phoneType: 'filtered',
    aboutMe: 'רופא מתמחה ברפואת ילדים, בחור שאפתן שמוצא עניין עמוק הן ברפואה הן בתורה. שומר שבת ולומד בבוקר לפני המשמרת.',
    aboutPartner: 'מחפש בחורה חכמה ומחויבת, שמסוגלת להתמודד עם לוח זמנים של רופא. חשוב שתהיה עצמאית ועם ערכים יהודיים חזקים.',
    matchmakerStatus: 'orange',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(6),
  },
  {
    id: 'm13',
    firstName: 'ישראל',
    lastName: 'בלום',
    age: 23,
    hebrewBirthday: 'כ"ז שבט תשפ"ה',
    status: 'single',
    community: 'בני ברק – ליטאי',
    occupation: 'בחור ישיבה',
    city: 'בני ברק',
    phone: '0521110013',
    email: 'israel@example.com',
    photos: [],
    style: 'yeshivish',
    partnerStyle: 'closed',
    preferredStream: 'ליטאי',
    traits: ['serious', 'calm', 'deep'],
    relationshipValues: ['spiritual', 'stability', 'worldview'],
    brings: ['commitment', 'depth', 'reliability'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'only_bw',
    partnerClothing: 'wig_only',
    phoneType: 'kosher',
    aboutMe: 'בחור ישיבה ליטאי בבני ברק, לומד ומחויב לתורה בכל ליבו. שואף לבנות בית של תורה ועבודת ה׳. אופי שקט ויציב.',
    aboutPartner: 'מחפש בחורה ליטאית, ירת שמים ובעלת מידות טובות. בחורה שרוצה לתמוך בבעלה הלומד.',
    matchmakerStatus: 'light_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(28),
  },
  {
    id: 'm14',
    firstName: 'נתן',
    lastName: 'שוורץ',
    age: 27,
    hebrewBirthday: 'ה׳ סיון תשפ"ב',
    status: 'single',
    community: 'כפר סבא – דתי לאומי',
    occupation: 'מורה',
    city: 'כפר סבא',
    phone: '0526660014',
    email: 'natan@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['social', 'calm', 'happy'],
    relationshipValues: ['family', 'homey', 'stability'],
    brings: ['homey', 'reliability', 'lightness'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'black_kippah',
    partnerClothing: 'wig_kerchief',
    phoneType: 'filtered',
    aboutMe: 'מורה לגיאוגרפיה ואזרחות בתיכון, בחור שמח שמאמין בחינוך ובצמיחה. גדלתי בבית דתי-לאומי פתוח, אוהב טיולים ומוזיקה.',
    aboutPartner: 'מחפש בחורה שמחה ופתוחה, שאוהבת חיים ומשפחה. חשוב שתהיה דתייה-לאומית עם לב פתוח.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(80),
  },
  {
    id: 'm15',
    firstName: 'רפאל',
    lastName: 'אביב',
    age: 29,
    hebrewBirthday: 'י"ח אדר תשפ"ב',
    status: 'single',
    community: 'רחובות – ספרדי',
    occupation: 'אדריכל',
    city: 'רחובות',
    phone: '0508880015',
    email: 'rafael@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['proactive', 'deep', 'communicative'],
    relationshipValues: ['aspirations', 'worldview', 'depth'],
    brings: ['depth', 'responsibility', 'stability'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'modern_modest',
    phoneType: 'smartphone',
    aboutMe: 'אדריכל בחברה מובילה, ספרדי מסורתי עם אהבה לאמנות ועיצוב. שומר שבת ומסורת מתוך גאווה יהודית. אוהב לטייל בחו"ל ולגלות תרבויות.',
    aboutPartner: 'מחפש בחורה אינטלקטואלית ויצירתית, עם עולם פנימי. חשוב שתהיה מסורתית ופתוחה לחיים מלאים.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'nm15', author: 'שדכן א', text: 'שיחה ראשונית מוצלחת – ממשיכים.', createdAt: new Date('2025-03-12T15:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(4),
  },
]
