import type { FemaleProfile, MaleProfile } from '@/types/registration'

const now = Date.now()
const days = (n: number) => new Date(now - n * 24 * 60 * 60 * 1000)

// ─── Female Mock Profiles ─────────────────────────────────────────────────────

export const MOCK_FEMALE_PROFILE: FemaleProfile = {
  id: 'f1',
  firstName: 'רחל',
  lastName: 'כהן',
  age: 24,
  hebrewBirthday: 'כ"ג תשרי תשפ"ד',
  status: 'single',
  community: 'ירושלים – דתי לאומי',
  occupation: 'מורה',
  city: 'ירושלים',
  phone: '0521234567',
  email: 'rachel@example.com',
  photos: [],
  style: 'modern',
  partnerStyle: 'open',
  preferredStream: '',
  traits: ['calm', 'serious', 'communicative'],
  relationshipValues: ['stability', 'family', 'depth'],
  brings: ['stability', 'commitment', 'communication'],
  doesntSuit: '',
  flexibility: 'important',
  clothing: 'classic',
  headcovering: 'kerchief_only',
  partnerClothing: 'bw_elegant',
  phoneType: 'filtered',
  aboutMe: 'אני מורה לאמנות בבית ספר יסודי בירושלים, בחורה רצינית עם לב פתוח ואהבת אנשים. בזמני הפנוי אני אוהבת לצייר, לקרוא ולהתפתח. מאמינה שחיים טובים בנויים על אמת, תקשורת ואמונה פשוטה וחמה.',
  aboutPartner: 'מחפשת בחור עם ראש פתוח ולב גדול, שמחויב לחיים יהודיים אך לא נוקשה. חשוב לי שיהיה תקשורתי ויודע להקשיב. בחור שיש לו יציבות ואחריות, אבל גם יכולת לשמוח ולהיות קל לב.',
  matchmakerStatus: 'orange',
  notes: [
    { id: 'n1', author: 'שרה מ.', text: 'פגישה ראשונה – רושם חיובי מאוד, בחורה רצינית ומוכנה.', createdAt: new Date('2024-11-15T10:30:00') },
    { id: 'n2', author: 'מרים כ.', text: 'מומלצת בחום על ידי הרב שלמה לוי.', createdAt: new Date('2024-11-20T14:00:00') },
  ],
  lockedAt: null,
  lastOfferDate: days(2),
}

export const MOCK_FEMALE_PROFILES: FemaleProfile[] = [
  MOCK_FEMALE_PROFILE,
  {
    id: 'f2',
    firstName: 'מרים',
    lastName: 'לוי',
    age: 26,
    hebrewBirthday: 'ט׳ אדר תשפ"ב',
    status: 'single',
    community: 'תל אביב – מסורתי',
    occupation: 'אחות',
    city: 'תל אביב',
    phone: '0534567890',
    email: 'miriam@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['happy', 'social', 'proactive'],
    relationshipValues: ['emotional', 'lightness', 'family'],
    brings: ['lightness', 'communication', 'homey'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'stylish',
    headcovering: 'wig_only',
    partnerClothing: 'colorful_weekday',
    phoneType: 'smartphone',
    aboutMe: 'אחות מוסמכת עובדת בבית חולים, בחורה חיה ושמחה שאוהבת לפגוש אנשים ולעזור. חיה את החיים בסגנון מעשי ולא מסבכת דברים. אוהבת טיולים, מוזיקה טובה וארוחות משפחתיות שוקקות.',
    aboutPartner: 'מחפשת בחור חי ושמח, שאוהב אנשים ולא נסגר בתוך עצמו. מישהו שיש לו כיוון בחיים אבל שיודע גם לצחוק ולהנות. לא חייב להיות ישיבתי, חשוב שיהיה ישר ונורמלי.',
    matchmakerStatus: 'light_red',
    notes: [
      { id: 'n3', author: 'רות ב.', text: 'הכירה שידוך בחודש שעבר, לא יצא לפועל. ממשיכים לחפש.', createdAt: new Date('2024-10-05T09:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(25),
  },
  {
    id: 'f3',
    firstName: 'שרה',
    lastName: 'גרוס',
    age: 22,
    hebrewBirthday: 'ב׳ ניסן תשפ"ה',
    status: 'single',
    community: 'בני ברק – חרדי',
    occupation: 'סטודנטית',
    city: 'בני ברק',
    phone: '0521112222',
    email: 'sara@example.com',
    photos: [],
    style: 'shmura',
    partnerStyle: 'shmur',
    preferredStream: 'ליטאי',
    traits: ['serious', 'deep', 'calm'],
    relationshipValues: ['spiritual', 'worldview', 'depth'],
    brings: ['commitment', 'reliability', 'depth'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'very_simple',
    headcovering: 'wig_no_cut',
    partnerClothing: 'only_bw',
    phoneType: 'kosher',
    aboutMe: 'סטודנטית בחינוך בבני ברק, בחורה שקטה ועמוקה שמחפשת משמעות אמיתית בחיים. מחויבת לאורח חיים תורני בכל תחומי החיים. גדלתי בבית ליטאי ואני שואפת לבנות בית כזה.',
    aboutPartner: 'מחפשת בחור ישיבה שמחויב לתורה ולמדות, בעל אופי שקט ויציב. חשוב לי שיהיה ירא שמים אמיתי ולא רק למראית עיין. בחור עמוק שיש לו עולם פנימי עשיר.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(75),
  },
  {
    id: 'f4',
    firstName: 'דבורה',
    lastName: 'פרידמן',
    age: 28,
    hebrewBirthday: 'י"ח חשון תשפ"ג',
    status: 'divorced',
    community: 'רמת גן – ספרדי',
    occupation: 'עורכת דין',
    city: 'רמת גן',
    phone: '0503334444',
    email: 'devora@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['proactive', 'communicative', 'deep'],
    relationshipValues: ['stability', 'aspirations', 'emotional'],
    brings: ['responsibility', 'stability', 'communication'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'respectable',
    headcovering: 'wig_plus_cover',
    partnerClothing: 'bw_elegant',
    phoneType: 'filtered',
    aboutMe: 'עורכת דין פעילה ברמת גן, גרושה שמחפשת להתחיל פרק חדש. אישה עצמאית, רצינית ומחויבת, שגדלה בקהילה ספרדית מסורתית. מאמינה בחיי משפחה יציבים המבוססים על כבוד הדדי.',
    aboutPartner: 'מחפשת גבר בוגר, מחויב ויציב שעברו חינוך לקחת אחריות. חשוב שיהיה מסורתי-פלוס – כיבוד דת אבל לא קיצוני. אדם שמסוגל לבנות שותפות אמיתית.',
    matchmakerStatus: 'green',
    notes: [
      { id: 'n4', author: 'חנה ש.', text: 'שידוך פעיל עם יוסף מ. – בשלב הבירורים.', createdAt: new Date('2025-01-10T11:00:00') },
    ],
    lockedAt: days(-2 / 24), // locked 2h ago
    lastOfferDate: days(5),
  },
  {
    id: 'f5',
    firstName: 'לאה',
    lastName: 'שפירא',
    age: 25,
    hebrewBirthday: 'כ"ה תמוז תשפ"ד',
    status: 'single',
    community: 'חיפה – דתי לאומי',
    occupation: 'מהנדסת',
    city: 'חיפה',
    phone: '0525556666',
    email: 'leah@example.com',
    photos: [],
    style: 'modern',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['flowing', 'happy', 'social'],
    relationshipValues: ['family', 'lightness', 'emotional'],
    brings: ['lightness', 'homey', 'reliability'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'modern',
    headcovering: 'no_preference',
    partnerClothing: 'very_modern',
    phoneType: 'smartphone',
    aboutMe: 'מהנדסת תוכנה בחברת הייטק בחיפה, שוחרת חופש ויצירתיות. חיה את החיים בשמחה ובקלילות, אוהבת לטייל ולנסות דברים חדשים. שומרת שבת ומסורת יהודית מתוך בחירה ואהבה.',
    aboutPartner: 'מחפשת בחור שמח ופתוח לחיים שלא "כבה" בתקיפות. אוהב לטייל וגם עם ראש בעסקים. לא מחפשת ישיבתי – חשוב שיהיה ישר, מאמין וחי את החיים בשלמות.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: null,
  },
]

// ─── Male Mock Profiles ───────────────────────────────────────────────────────

export const MOCK_MALE_PROFILES: MaleProfile[] = [
  {
    id: 'm1',
    firstName: 'יעקב',
    lastName: 'כהן',
    age: 25,
    hebrewBirthday: 'ז׳ אייר תשפ"ד',
    status: 'single',
    community: 'ירושלים – דתי לאומי',
    occupation: 'בעל מקצוע',
    city: 'ירושלים',
    phone: '0521230001',
    email: 'yaakov@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open_ish',
    preferredStream: '',
    traits: ['calm', 'proactive', 'communicative'],
    relationshipValues: ['stability', 'family', 'depth'],
    brings: ['commitment', 'responsibility', 'stability'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'wig_any',
    phoneType: 'filtered',
    aboutMe: 'בעל מקצוע (חשמלאי) בירושלים, בחור ישר ופועל ידיים שגאה בעבודתו. קיים שבת וחגים, מתפלל בבוקר, ועולם התורה קרוב לליבי גם אם איני אוחז בחינוך ישיבתי. אוהב ספורט, טבע ומשפחה.',
    aboutPartner: 'מחפש בחורה פשוטה ויציבה שמחפשת בית ומשפחה. לא צריכה להיות אינטלקטואלית מאוד, אבל חשוב שתהיה ישרה, מחויבת ובעלת אופי חם עם מחויבות לשמירת מצוות.',
    matchmakerStatus: 'orange',
    notes: [
      { id: 'nm1', author: 'שמואל ט.', text: 'הצעה נשלחה אתמול, מחכים לתשובה.', createdAt: new Date('2025-01-12T08:00:00') },
    ],
    lockedAt: null,
    lastOfferDate: days(3),
  },
  {
    id: 'm2',
    firstName: 'אברהם',
    lastName: 'לוי',
    age: 27,
    hebrewBirthday: 'כ׳ שבט תשפ"א',
    status: 'single',
    community: 'תל אביב – מסורתי',
    occupation: 'מתכנת',
    city: 'תל אביב',
    phone: '0534560002',
    email: 'avraham@example.com',
    photos: [],
    style: 'modern',
    partnerStyle: 'modern',
    preferredStream: '',
    traits: ['deep', 'serious', 'flowing'],
    relationshipValues: ['aspirations', 'worldview', 'emotional'],
    brings: ['depth', 'communication', 'reliability'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'always_colorful',
    partnerClothing: 'kerchief',
    phoneType: 'smartphone',
    aboutMe: 'מתכנת Full Stack בסטארטאפ תל אביבי, אינטלקטואל שאוהב ספרות, פילוסופיה ומוזיקה קלאסית. שומר שבת בשמחה ומאמין שיהדות ומודרניות יכולות לדור בכפיפה אחת.',
    aboutPartner: 'מחפש בחורה עם עולם פנימי עשיר, שמסוגלת לנהל שיחה עמוקה. חשוב לי שתהיה עצמאית, חושבת, ועם חיבור אמיתי לזהות יהודית. לא חייבת להיות שומרת שבת קפדנית.',
    matchmakerStatus: 'light_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(20),
  },
  {
    id: 'm3',
    firstName: 'יוסף',
    lastName: 'גרוס',
    age: 23,
    hebrewBirthday: 'ג׳ אלול תשפ"ה',
    status: 'single',
    community: 'בני ברק – חרדי',
    occupation: 'בחור ישיבה',
    city: 'בני ברק',
    phone: '0521110003',
    email: 'yosef@example.com',
    photos: [],
    style: 'yeshivish',
    partnerStyle: 'closed',
    preferredStream: 'ליטאי',
    traits: ['serious', 'deep', 'shy'],
    relationshipValues: ['spiritual', 'worldview', 'stability'],
    brings: ['commitment', 'depth', 'reliability'],
    doesntSuit: '',
    flexibility: 'very_important',
    clothing: 'only_bw',
    partnerClothing: 'wig_only',
    phoneType: 'kosher',
    aboutMe: 'בחור ישיבה מבני ברק, מחויב לתורה ולמדות בכל כוחי. גדלתי בבית ליטאי ורוצה לבנות בית עם יסודות חזקים. לא קיצוני אבל הרצינות היא הערך שמנחה אותי.',
    aboutPartner: 'מחפש בחורה שמורה, ירת שמים ועם ענווה. בחורה שמבינה שבית יהודי אמיתי נבנה לאט. חשוב שתהיה צנועה בלבושה ובהתנהגותה ומחויבת לאורח חיים תורני.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: days(90),
  },
  {
    id: 'm4',
    firstName: 'דוד',
    lastName: 'פרידמן',
    age: 29,
    hebrewBirthday: 'כ"ד כסלו תשפ"ב',
    status: 'divorced',
    community: 'רמת גן – ספרדי',
    occupation: 'רואה חשבון',
    city: 'רמת גן',
    phone: '0503330004',
    email: 'david@example.com',
    photos: [],
    style: 'open',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['social', 'proactive', 'happy'],
    relationshipValues: ['family', 'homey', 'emotional'],
    brings: ['stability', 'homey', 'communication'],
    doesntSuit: '',
    flexibility: 'important',
    clothing: 'colorful_weekday',
    partnerClothing: 'modern_modest',
    phoneType: 'filtered',
    aboutMe: 'רואה חשבון ברמת גן, גרוש ומחפש התחלה חדשה. ספרדי מסורתי שגדל עם ערכי משפחה ואמונה. בעל ראש פרקטי, אוהב לארגן ולתכנן, אבל גם יודע לחגוג ולפנק.',
    aboutPartner: 'מחפש אישה בוגרת ורצינית שמוכנה לבנות ביחד. חשוב שתהיה חמה ומשפחתית עם ערכים מסורתיים. כיבוד שבת וחג צריך להיות טבעי עבורה.',
    matchmakerStatus: 'green',
    notes: [
      { id: 'nm2', author: 'בנימין כ.', text: 'שידוך פעיל עם דבורה פ. – בשלב הבירורים.', createdAt: new Date('2025-01-10T11:00:00') },
    ],
    lockedAt: new Date(now - 10 * 60 * 60 * 1000), // locked 10h ago
    lastOfferDate: days(6),
  },
  {
    id: 'm5',
    firstName: 'משה',
    lastName: 'שפירא',
    age: 24,
    hebrewBirthday: 'ט"ו אב תשפ"ד',
    status: 'single',
    community: 'חיפה – דתי לאומי',
    occupation: 'סטודנט',
    city: 'חיפה',
    phone: '0525550005',
    email: 'moshe@example.com',
    photos: [],
    style: 'open_ish',
    partnerStyle: 'open',
    preferredStream: '',
    traits: ['flowing', 'calm', 'communicative'],
    relationshipValues: ['lightness', 'family', 'stability'],
    brings: ['lightness', 'reliability', 'homey'],
    doesntSuit: '',
    flexibility: 'preferred',
    clothing: 'colorful_weekday',
    partnerClothing: 'no_preference',
    phoneType: 'filtered',
    aboutMe: 'סטודנט להנדסה אזרחית בטכניון, זורם ואופטימי בטבעי. גדלתי בחיפה בבית דתי-לאומי פתוח ומחבק. אוהב טיולים, מוזיקה וחברים, ובמקביל שומר תפילה ושבת כחלק מחיי.',
    aboutPartner: 'מחפש בחורה שמחה ורגועה, שחיה את החיים בפשטות ובשמחה. לא חשוב לי שתהיה ישיבתית – חשוב שתהיה אמיתית ועם ערכים. בחורה שמחפשת לבנות בית ומוכנה לצמוח ביחד.',
    matchmakerStatus: 'bright_red',
    notes: [],
    lockedAt: null,
    lastOfferDate: null,
  },
]
